#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  git difftool --tool=vimdiff -y "$@"
}

source sub "$BASH_SOURCE" "$@"
