#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure devel/git-base
  pkg ensure devel/git-contrib
  pkg ensure devel/git-docs

  block compile npm
  ln -nfs ../node_modules/.bin/gh "$shome/bin/gh"
}

bootstrap
