#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew install git
      ;;
    *)
      pkg ensure devel/git-base
      pkg ensure devel/git-contrib
      pkg ensure devel/git-docs
      ;;
  esac

  block compile yarn
  ln -nfs ../node_modules/.bin/gh "$shome/bin/gh"
}

bootstrap
