#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "$PKG_HOME/install/bin/git" ]]; then
    return 1
  fi

  if ! type -P gh >/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
