#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      if [[ ! -x "${BOARD_PATH}/homebrew/bin/git" ]]; then
        return 1
      fi
      ;;
    *)
      if [[ ! -x "$PKG_HOME/install/bin/git" ]]; then
        return 1
      fi
      ;;
  esac

  if ! type -P gh >/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
